# docker-compose.yml

# The 'version' tag has been removed.
services:
  # The Flask application service
  web:
    build: .
    container_name: crm_web_app
    env_file:
      - .env
    expose:
      - 5000
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

  # The ngrok service
  ngrok:
    image: ngrok/ngrok:latest
    container_name: crm_ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    command: "http web:5000"