[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "attackacrack-crm"
version = "0.1.0"

[tool.setuptools.packages.find]
exclude = ["instance*", "templates*", "tests*", "uploads*"]
