# This is the specification for the Attack-a-Crack application on Digital Ocean App Platform.
# Version 4: Using native DigitalOcean environment variable management (no placeholders)

name: attackacrack-prod

# Define the region for your app. Choose one close to your users.
# e.g., nyc3, sfo3, ams3, sgp1, fra1
region: nyc3

# Define the services (public-facing web containers) for your application.
services:
  - name: attackacrack-web
    # Use pre-built image from DigitalOcean Container Registry
    # The deploy workflow will update this with the correct tag
    image:
      registry_type: DOCR
      repository: attackacrack-crm
      tag: latest
    # Define the command to run the web server.
    # This overrides the Dockerfile's CMD or ENTRYPOINT for this specific service.
    # We use gunicorn for a production-ready WSGI server.
    run_command: ./entrypoint.sh
    # Define the instance size. Upgraded to xs for better performance
    instance_size_slug: basic-xs
    # Define the number of instances. Start with 1 and enable auto-scaling.
    instance_count: 1
    # Define the HTTP port the application listens on inside the container.
    http_port: 5000
    # Define the routes for incoming traffic.
    routes:
      - path: /
    # Health check for monitoring
    health_check:
      http_path: /health
      timeout_seconds: 10
      port: 5000
    # Define environment variables.
    # Using native DO env var management - no values means it uses existing values
    envs:
      # Static configuration values
      - key: FLASK_ENV
        value: "production"
        scope: RUN_AND_BUILD_TIME
      - key: FLASK_APP
        value: "app.py"
        scope: RUN_AND_BUILD_TIME
      # Database bindings (special DO syntax)
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_URI
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      # Secrets - no value specified, uses existing DO values
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CELERY_BROKER_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CELERY_RESULT_BACKEND
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_WEBHOOK_SIGNING_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_PHONE_NUMBER
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_PHONE_NUMBER_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ENCRYPTION_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GEMINI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_PROJECT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PROPERTY_RADAR_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_REDIRECT_URI
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_SANDBOX
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SMARTLEAD_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

# Define the workers (background task processors) for your application.
workers:
  - name: attackacrack-worker
    # Use pre-built image from DigitalOcean Container Registry
    image:
      registry_type: DOCR
      repository: attackacrack-crm
      tag: latest
    # Define the command to run the Celery worker.
    # Limit concurrency to 2 workers for basic-xs instance
    run_command: celery -A celery_worker.celery worker --loglevel=info --concurrency=2
    # Define the instance size - xs for worker to handle memory requirements
    instance_size_slug: basic-xs
    # Define the number of instances.
    instance_count: 1
    # Define environment variables (must match the web service).
    envs:
      # Static configuration values
      - key: FLASK_ENV
        value: "production"
        scope: RUN_AND_BUILD_TIME
      - key: FLASK_APP
        value: "app.py"
        scope: RUN_AND_BUILD_TIME
      # Database bindings
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: POSTGRES_URI
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      # Secrets - no value specified, uses existing DO values
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CELERY_BROKER_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CELERY_RESULT_BACKEND
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_WEBHOOK_SIGNING_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_PHONE_NUMBER
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENPHONE_PHONE_NUMBER_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ENCRYPTION_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GEMINI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GOOGLE_PROJECT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PROPERTY_RADAR_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_REDIRECT_URI
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QUICKBOOKS_SANDBOX
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SMARTLEAD_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

# Define the managed databases and other addons for the application.
databases:
  - name: db
    # Use PostgreSQL version 13.
    engine: PG
    version: "13"
    # The production database name will be auto-created as 'db'
    # matching the component name
    production: true
    # Cluster name for the production database
    cluster_name: attackacrack-db
    # The size of the database cluster. Start small.
    size: db-s-1vcpu-1gb