name: attackacrack
services:
- name: attackacrack
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: mrjmd/attackacrack
  run_command: gunicorn --worker-tmp-dir /dev/shm -b 0.0.0.0:5000 app:app
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
- name: worker
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: mrjmd/attackacrack
  run_command: celery -A celery_worker.celery worker --loglevel=info
  instance_count: 1
  instance_size_slug: basic-xxs
- name: beat
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: mrjmd/attackacrack
  run_command: celery -A celery_worker.celery beat --loglevel=info -s /tmp/celerybeat-schedule
  instance_count: 1
  instance_size_slug: basic-xxs
databases:
- name: attackacrack-db
  engine: PG
  production: true
  version: "12"
- name: attackacrack-cache
  engine: REDIS
  production: true
  version: "6"