"""Add text campaign features: ContactFlag model, enhanced Campaign/CampaignMembership fields, Contact contact_metadata

Revision ID: 0244bf8c0fe9
Revises: f26c65522096
Create Date: 2025-07-29 20:28:21.013826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0244bf8c0fe9'
down_revision = '71ee45eb8abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('applies_to', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign', sa.Column('campaign_type', sa.String(length=20), nullable=True))
    op.add_column('campaign', sa.Column('audience_type', sa.String(length=20), nullable=True))
    op.add_column('campaign', sa.Column('daily_limit', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('business_hours_only', sa.Boolean(), nullable=True))
    op.add_column('campaign', sa.Column('ab_config', sa.JSON(), nullable=True))
    op.add_column('campaign_membership', sa.Column('pre_send_flags', sa.JSON(), nullable=True))
    op.add_column('campaign_membership', sa.Column('override_action', sa.String(length=20), nullable=True))
    op.add_column('campaign_membership', sa.Column('response_sentiment', sa.String(length=20), nullable=True))
    op.add_column('campaign_membership', sa.Column('message_sent', sa.Text(), nullable=True))
    op.add_column('contact', sa.Column('contact_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'contact_metadata')
    op.drop_column('campaign_membership', 'message_sent')
    op.drop_column('campaign_membership', 'response_sentiment')
    op.drop_column('campaign_membership', 'override_action')
    op.drop_column('campaign_membership', 'pre_send_flags')
    op.drop_column('campaign', 'ab_config')
    op.drop_column('campaign', 'business_hours_only')
    op.drop_column('campaign', 'daily_limit')
    op.drop_column('campaign', 'audience_type')
    op.drop_column('campaign', 'campaign_type')
    op.drop_table('contact_flag')
    # ### end Alembic commands ###
