"""Add status to Quote model

Revision ID: 1875311618d2
Revises: 5b88747384d3
Create Date: 2025-07-25 11:52:44.484651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
# NOTE: You may need to adjust the 'revises' ID below to match the
# ID of your PREVIOUS migration script. Check your migrations/versions folder.
revision = '1875311618d2'
revises = '5b88747384d3' # <--- IMPORTANT: Change this if 'e278ef28a82e' is not your last migration
down_revision = '5b88747384d3' # <--- IMPORTANT: Change this as well
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Draft'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
