"""Add many-to-many relationship between contacts and CSV imports

Revision ID: 1d88e6ff12a3
Revises: 641943f5d93d
Create Date: 2025-07-30 18:52:49.854106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d88e6ff12a3'
down_revision = '641943f5d93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_csv_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('csv_import_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('data_updated', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['csv_import_id'], ['csv_import.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'csv_import_id', name='unique_contact_csv_import')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_csv_import')
    # ### end Alembic commands ###
