"""Increase password_hash column size for User model

Revision ID: 2792ed2d7978
Revises: 5666d6960685
Create Date: 2025-08-18 18:28:49.670151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2792ed2d7978'
down_revision = '5666d6960685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase password_hash column size for User model
    op.alter_column('user', 'password_hash',
                    existing_type=sa.String(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    
    op.add_column('activity', sa.Column('activity_metadata', sa.JSON(), nullable=True))
    op.add_column('campaign_membership', sa.Column('sent_activity_id', sa.Integer(), nullable=True))
    op.add_column('campaign_membership', sa.Column('membership_metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'campaign_membership', 'activity', ['sent_activity_id'], ['id'])
    op.drop_constraint(op.f('todos_user_id_fkey'), 'todos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('todos_user_id_fkey'), 'todos', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'campaign_membership', type_='foreignkey')
    op.drop_column('campaign_membership', 'membership_metadata')
    op.drop_column('campaign_membership', 'sent_activity_id')
    op.drop_column('activity', 'activity_metadata')
    
    # Revert password_hash column size
    op.alter_column('user', 'password_hash',
                    existing_type=sa.String(length=256),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###
