"""Add google_calendar_event_id to Appointment

Revision ID: 59e53a278865
Revises: 4ea9c7069731
Create Date: 2025-07-24 14:46:42.669096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e53a278865'
down_revision = '4ea9c7069731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    # ### end Alembic commands ###
