"""Add campaign list management tables

Revision ID: 641943f5d93d
Revises: 80ad7a2ef2f1
Create Date: 2025-07-30 18:17:10.852443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641943f5d93d'
down_revision = '80ad7a2ef2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('filter_criteria', sa.JSON(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('successful_imports', sa.Integer(), nullable=True),
    sa.Column('failed_imports', sa.Integer(), nullable=True),
    sa.Column('import_type', sa.String(length=50), nullable=True),
    sa.Column('import_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_list_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('import_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['campaign_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'contact_id', name='unique_list_member')
    )
    op.add_column('campaign', sa.Column('list_id', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('adapt_script_template', sa.Text(), nullable=True))
    op.add_column('campaign', sa.Column('days_between_contacts', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'campaign_list', ['list_id'], ['id'])
    op.add_column('campaign_membership', sa.Column('previous_contact_date', sa.DateTime(), nullable=True))
    op.add_column('campaign_membership', sa.Column('previous_contact_type', sa.String(length=50), nullable=True))
    op.add_column('campaign_membership', sa.Column('previous_response', sa.String(length=50), nullable=True))
    op.add_column('campaign_membership', sa.Column('script_adapted', sa.Boolean(), nullable=True))
    op.add_column('contact', sa.Column('csv_import_id', sa.Integer(), nullable=True))
    op.add_column('contact', sa.Column('import_source', sa.String(length=100), nullable=True))
    op.add_column('contact', sa.Column('imported_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'contact', 'csv_import', ['csv_import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'imported_at')
    op.drop_column('contact', 'import_source')
    op.drop_column('contact', 'csv_import_id')
    op.drop_column('campaign_membership', 'script_adapted')
    op.drop_column('campaign_membership', 'previous_response')
    op.drop_column('campaign_membership', 'previous_contact_type')
    op.drop_column('campaign_membership', 'previous_contact_date')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'days_between_contacts')
    op.drop_column('campaign', 'adapt_script_template')
    op.drop_column('campaign', 'list_id')
    op.drop_table('campaign_list_member')
    op.drop_table('csv_import')
    op.drop_table('campaign_list')
    # ### end Alembic commands ###
