"""Initial migration with Phase 1 enhancements

Revision ID: 71ee45eb8abc
Revises: 
Create Date: 2025-07-29 13:21:41.836094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ee45eb8abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('template_a', sa.Text(), nullable=True),
    sa.Column('template_b', sa.Text(), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('on_existing_contact', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openphone_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openphone_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openphone_user_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openphone_user_id')
    )
    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('api_version', sa.String(length=10), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('campaign_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('variant_sent', sa.String(length=1), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('reply_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['reply_activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('activity_type', sa.String(length=20), nullable=True))
    op.add_column('activity', sa.Column('from_number', sa.String(length=20), nullable=True))
    op.add_column('activity', sa.Column('to_numbers', sa.JSON(), nullable=True))
    op.add_column('activity', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('phone_number_id', sa.String(length=100), nullable=True))
    op.add_column('activity', sa.Column('media_urls', sa.JSON(), nullable=True))
    op.add_column('activity', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('answered_at', sa.DateTime(), nullable=True))
    op.add_column('activity', sa.Column('answered_by', sa.String(length=100), nullable=True))
    op.add_column('activity', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('activity', sa.Column('initiated_by', sa.String(length=100), nullable=True))
    op.add_column('activity', sa.Column('forwarded_from', sa.String(length=100), nullable=True))
    op.add_column('activity', sa.Column('forwarded_to', sa.String(length=100), nullable=True))
    op.add_column('activity', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('activity', sa.Column('ai_next_steps', sa.Text(), nullable=True))
    op.add_column('activity', sa.Column('ai_transcript', sa.JSON(), nullable=True))
    op.add_column('activity', sa.Column('ai_content_status', sa.String(length=50), nullable=True))
    op.add_column('activity', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('activity', 'openphone_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('activity', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_foreign_key(None, 'activity', 'contact', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'activity', 'user', ['user_id'], ['id'])
    op.drop_column('activity', 'duration')
    op.drop_column('activity', 'type')
    op.add_column('conversation', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('conversation', sa.Column('phone_number_id', sa.String(length=100), nullable=True))
    op.add_column('conversation', sa.Column('last_activity_type', sa.String(length=20), nullable=True))
    op.add_column('conversation', sa.Column('last_activity_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'last_activity_id')
    op.drop_column('conversation', 'last_activity_type')
    op.drop_column('conversation', 'phone_number_id')
    op.drop_column('conversation', 'name')
    op.add_column('activity', sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'message'::character varying"), autoincrement=False, nullable=False))
    op.add_column('activity', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.alter_column('activity', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('activity', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity', 'openphone_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('activity', 'updated_at')
    op.drop_column('activity', 'ai_content_status')
    op.drop_column('activity', 'ai_transcript')
    op.drop_column('activity', 'ai_next_steps')
    op.drop_column('activity', 'ai_summary')
    op.drop_column('activity', 'forwarded_to')
    op.drop_column('activity', 'forwarded_from')
    op.drop_column('activity', 'initiated_by')
    op.drop_column('activity', 'completed_at')
    op.drop_column('activity', 'answered_by')
    op.drop_column('activity', 'answered_at')
    op.drop_column('activity', 'duration_seconds')
    op.drop_column('activity', 'media_urls')
    op.drop_column('activity', 'phone_number_id')
    op.drop_column('activity', 'user_id')
    op.drop_column('activity', 'to_numbers')
    op.drop_column('activity', 'from_number')
    op.drop_column('activity', 'activity_type')
    op.drop_column('activity', 'contact_id')
    op.drop_table('campaign_membership')
    op.drop_table('webhook_event')
    op.drop_table('user')
    op.drop_table('phone_number')
    op.drop_table('campaign')
    # ### end Alembic commands ###
