"""Initial migration

Revision ID: 83d517a98249
Revises: 13618c8f8334
Create Date: 2025-07-27 16:55:45.788950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d517a98249'
down_revision = '13618c8f8334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'job_id')
    # ### end Alembic commands ###
