"""Add campaign scheduling fields for Phase 3C

Revision ID: 88d16698a080
Revises: 35e46443c6d5
Create Date: 2025-08-24 03:02:11.479406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d16698a080'
down_revision = '35e46443c6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('campaign', sa.Column('recurrence_pattern', sa.JSON(), nullable=True))
    op.add_column('campaign', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('campaign', sa.Column('parent_campaign_id', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('campaign', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'campaign', ['parent_campaign_id'], ['id'])
    op.drop_index(op.f('ix_campaign_templates_category'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_is_active'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_parent_id'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_status'), table_name='campaign_templates')
    op.drop_constraint(op.f('phone_validation_phone_number_key'), 'phone_validation', type_='unique')
    op.drop_index(op.f('ix_phone_validation_phone_number'), table_name='phone_validation')
    op.create_index(op.f('ix_phone_validation_phone_number'), 'phone_validation', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_validation_phone_number'), table_name='phone_validation')
    op.create_index(op.f('ix_phone_validation_phone_number'), 'phone_validation', ['phone_number'], unique=False)
    op.create_unique_constraint(op.f('phone_validation_phone_number_key'), 'phone_validation', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_campaign_templates_status'), 'campaign_templates', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_templates_parent_id'), 'campaign_templates', ['parent_id'], unique=False)
    op.create_index(op.f('ix_campaign_templates_is_active'), 'campaign_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_campaign_templates_category'), 'campaign_templates', ['category'], unique=False)
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'archived_at')
    op.drop_column('campaign', 'archived')
    op.drop_column('campaign', 'parent_campaign_id')
    op.drop_column('campaign', 'is_recurring')
    op.drop_column('campaign', 'next_run_at')
    op.drop_column('campaign', 'recurrence_pattern')
    op.drop_column('campaign', 'timezone')
    op.drop_column('campaign', 'scheduled_at')
    # ### end Alembic commands ###
