"""Add PhoneValidation model for NumVerify API caching

Revision ID: add_phone_validation
Revises: bc1952ff7326
Create Date: 2025-08-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_phone_validation'
down_revision = 'bc1952ff7326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_validation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('line_type', sa.String(length=20), nullable=True),
        sa.Column('carrier', sa.String(length=100), nullable=True),
        sa.Column('country_code', sa.String(length=5), nullable=True),
        sa.Column('country_name', sa.String(length=100), nullable=True),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('validation_date', sa.DateTime(), nullable=False),
        sa.Column('cached_until', sa.DateTime(), nullable=False),
        sa.Column('raw_response', sa.JSON(), nullable=True),
        sa.Column('api_response', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_phone_validation_cached_until'), 'phone_validation', ['cached_until'], unique=False)
    op.create_index(op.f('ix_phone_validation_country_code'), 'phone_validation', ['country_code'], unique=False)
    op.create_index(op.f('ix_phone_validation_phone_number'), 'phone_validation', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_validation_phone_number'), table_name='phone_validation')
    op.drop_index(op.f('ix_phone_validation_country_code'), table_name='phone_validation')
    op.drop_index(op.f('ix_phone_validation_cached_until'), table_name='phone_validation')
    op.drop_table('phone_validation')
    # ### end Alembic commands ###