"""Add OptOutAudit table for tracking opt-out events

Revision ID: bc1952ff7326
Revises: 5bf30755a98d
Create Date: 2025-08-22 03:11:00.832908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1952ff7326'
down_revision = '5bf30755a98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opt_out_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('opt_out_method', sa.String(length=50), nullable=False),
    sa.Column('keyword_used', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opt_out_audit_contact', 'opt_out_audit', ['contact_id'], unique=False)
    op.create_index('idx_opt_out_audit_created', 'opt_out_audit', ['created_at'], unique=False)
    op.create_index('idx_opt_out_audit_method', 'opt_out_audit', ['opt_out_method'], unique=False)
    op.create_index('idx_opt_out_audit_phone', 'opt_out_audit', ['phone_number'], unique=False)
    op.drop_index(op.f('idx_activity_contact'), table_name='activity')
    op.drop_index(op.f('idx_activity_conversation_created'), table_name='activity')
    op.drop_index(op.f('idx_activity_openphone_id'), table_name='activity', postgresql_where='(openphone_id IS NOT NULL)')
    op.drop_index(op.f('idx_activity_type_created'), table_name='activity')
    op.drop_index(op.f('idx_activity_user'), table_name='activity')
    op.drop_index(op.f('ix_activity_conversation_created'), table_name='activity')
    op.drop_index(op.f('ix_activity_openphone_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_type'), table_name='activity')
    op.drop_index(op.f('idx_appointment_date'), table_name='appointment')
    op.drop_index(op.f('idx_campaign_membership_sent'), table_name='campaign_membership')
    op.drop_index(op.f('idx_campaign_membership_status'), table_name='campaign_membership')
    op.drop_index(op.f('ix_campaign_membership_campaign_status'), table_name='campaign_membership')
    op.drop_index(op.f('ix_campaign_membership_contact_id'), table_name='campaign_membership')
    op.drop_index(op.f('idx_contact_email'), table_name='contact')
    op.drop_index(op.f('idx_contact_first_name'), table_name='contact')
    op.drop_index(op.f('idx_contact_last_name'), table_name='contact')
    op.drop_index(op.f('idx_contact_phone_hash'), table_name='contact', postgresql_using='hash')
    op.drop_index(op.f('ix_contact_phone_hash'), table_name='contact', postgresql_using='hash')
    op.drop_index(op.f('idx_contact_flag_type_phone'), table_name='contact_flag', postgresql_where="((flag_type)::text = 'opted_out'::text)")
    op.drop_index(op.f('ix_contact_flag_opted_out'), table_name='contact_flag', postgresql_where="((flag_type)::text = 'opted_out'::text)")
    op.drop_index(op.f('idx_conversation_contact'), table_name='conversation')
    op.drop_index(op.f('idx_conversation_phone_number_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_contact_id'), table_name='conversation')
    op.drop_index(op.f('idx_failed_webhook_queue_created_at'), table_name='failed_webhook_queue')
    op.drop_index(op.f('idx_failed_webhook_queue_event_id'), table_name='failed_webhook_queue')
    op.drop_index(op.f('idx_failed_webhook_queue_event_type'), table_name='failed_webhook_queue')
    op.drop_index(op.f('idx_failed_webhook_queue_next_retry'), table_name='failed_webhook_queue')
    op.drop_index(op.f('idx_failed_webhook_queue_resolved'), table_name='failed_webhook_queue')
    op.create_index(op.f('ix_failed_webhook_queue_created_at'), 'failed_webhook_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_failed_webhook_queue_event_id'), 'failed_webhook_queue', ['event_id'], unique=False)
    op.create_index(op.f('ix_failed_webhook_queue_event_type'), 'failed_webhook_queue', ['event_type'], unique=False)
    op.create_index(op.f('ix_failed_webhook_queue_next_retry_at'), 'failed_webhook_queue', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_failed_webhook_queue_resolved'), 'failed_webhook_queue', ['resolved'], unique=False)
    op.drop_index(op.f('idx_invoice_status_due'), table_name='invoice')
    op.drop_index(op.f('idx_webhook_event_id'), table_name='webhook_event')
    op.drop_index(op.f('idx_webhook_event_processed'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_event_event_type'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_event_processed'), table_name='webhook_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_webhook_event_processed'), 'webhook_event', ['processed', 'event_type'], unique=False)
    op.create_index(op.f('ix_webhook_event_event_type'), 'webhook_event', ['event_type'], unique=False)
    op.create_index(op.f('idx_webhook_event_processed'), 'webhook_event', ['processed', 'created_at'], unique=False)
    op.create_index(op.f('idx_webhook_event_id'), 'webhook_event', ['event_id'], unique=False)
    op.create_index(op.f('idx_invoice_status_due'), 'invoice', ['status', 'due_date'], unique=False)
    op.drop_index(op.f('ix_failed_webhook_queue_resolved'), table_name='failed_webhook_queue')
    op.drop_index(op.f('ix_failed_webhook_queue_next_retry_at'), table_name='failed_webhook_queue')
    op.drop_index(op.f('ix_failed_webhook_queue_event_type'), table_name='failed_webhook_queue')
    op.drop_index(op.f('ix_failed_webhook_queue_event_id'), table_name='failed_webhook_queue')
    op.drop_index(op.f('ix_failed_webhook_queue_created_at'), table_name='failed_webhook_queue')
    op.create_index(op.f('idx_failed_webhook_queue_resolved'), 'failed_webhook_queue', ['resolved'], unique=False)
    op.create_index(op.f('idx_failed_webhook_queue_next_retry'), 'failed_webhook_queue', ['next_retry_at', 'resolved'], unique=False)
    op.create_index(op.f('idx_failed_webhook_queue_event_type'), 'failed_webhook_queue', ['event_type'], unique=False)
    op.create_index(op.f('idx_failed_webhook_queue_event_id'), 'failed_webhook_queue', ['event_id'], unique=False)
    op.create_index(op.f('idx_failed_webhook_queue_created_at'), 'failed_webhook_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_contact_id'), 'conversation', ['contact_id'], unique=False)
    op.create_index(op.f('idx_conversation_phone_number_id'), 'conversation', ['phone_number_id'], unique=False)
    op.create_index(op.f('idx_conversation_contact'), 'conversation', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_flag_opted_out'), 'contact_flag', ['flag_type', 'contact_id'], unique=False, postgresql_where="((flag_type)::text = 'opted_out'::text)")
    op.create_index(op.f('idx_contact_flag_type_phone'), 'contact_flag', ['flag_type', 'contact_id'], unique=False, postgresql_where="((flag_type)::text = 'opted_out'::text)")
    op.create_index(op.f('ix_contact_phone_hash'), 'contact', ['phone'], unique=False, postgresql_using='hash')
    op.create_index(op.f('idx_contact_phone_hash'), 'contact', ['phone'], unique=False, postgresql_using='hash')
    op.create_index(op.f('idx_contact_last_name'), 'contact', ['last_name'], unique=False)
    op.create_index(op.f('idx_contact_first_name'), 'contact', ['first_name'], unique=False)
    op.create_index(op.f('idx_contact_email'), 'contact', ['email'], unique=False)
    op.create_index(op.f('ix_campaign_membership_contact_id'), 'campaign_membership', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_membership_campaign_status'), 'campaign_membership', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('idx_campaign_membership_status'), 'campaign_membership', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('idx_campaign_membership_sent'), 'campaign_membership', ['sent_at', 'status'], unique=False)
    op.create_index(op.f('idx_appointment_date'), 'appointment', ['date', 'time'], unique=False)
    op.create_index(op.f('ix_activity_type'), 'activity', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_openphone_id'), 'activity', ['openphone_id'], unique=False)
    op.create_index(op.f('ix_activity_conversation_created'), 'activity', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_activity_user'), 'activity', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_activity_type_created'), 'activity', ['activity_type', 'created_at'], unique=False)
    op.create_index(op.f('idx_activity_openphone_id'), 'activity', ['openphone_id'], unique=False, postgresql_where='(openphone_id IS NOT NULL)')
    op.create_index(op.f('idx_activity_conversation_created'), 'activity', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_activity_contact'), 'activity', ['contact_id', 'created_at'], unique=False)
    op.drop_index('idx_opt_out_audit_phone', table_name='opt_out_audit')
    op.drop_index('idx_opt_out_audit_method', table_name='opt_out_audit')
    op.drop_index('idx_opt_out_audit_created', table_name='opt_out_audit')
    op.drop_index('idx_opt_out_audit_contact', table_name='opt_out_audit')
    op.drop_table('opt_out_audit')
    # ### end Alembic commands ###
