name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    name: Deploy to DigitalOcean App Platform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action/deploy@v2
      env:
        # Pass all secrets as environment variables for substitution
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
        CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
        OPENPHONE_API_KEY: ${{ secrets.OPENPHONE_API_KEY }}
        OPENPHONE_WEBHOOK_SIGNING_KEY: ${{ secrets.OPENPHONE_WEBHOOK_SIGNING_KEY }}
        OPENPHONE_PHONE_NUMBER: ${{ secrets.OPENPHONE_PHONE_NUMBER }}
        OPENPHONE_PHONE_NUMBER_ID: ${{ secrets.OPENPHONE_PHONE_NUMBER_ID }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        PROPERTY_RADAR_API_KEY: ${{ secrets.PROPERTY_RADAR_API_KEY }}
        QUICKBOOKS_CLIENT_ID: ${{ secrets.QUICKBOOKS_CLIENT_ID }}
        QUICKBOOKS_CLIENT_SECRET: ${{ secrets.QUICKBOOKS_CLIENT_SECRET }}
        QUICKBOOKS_REDIRECT_URI: ${{ secrets.QUICKBOOKS_REDIRECT_URI }}
        QUICKBOOKS_SANDBOX: ${{ secrets.QUICKBOOKS_SANDBOX }}
        SMARTLEAD_API_KEY: ${{ secrets.SMARTLEAD_API_KEY }}
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app_name: attackacrack-prod
        print_build_logs: true
        print_deploy_logs: true
    
    - name: Verify Deployment
      run: |
        echo "## 🚀 Deployment Complete!"
        echo ""
        echo "The application has been deployed with all environment variables properly configured."
        echo ""
        echo "### Important Notes:"
        echo "- Environment variables are now managed through GitHub Secrets"
        echo "- The ${VARIABLE} placeholders in app.yaml are automatically substituted"
        echo "- All sensitive values are encrypted as SECRET type in DigitalOcean"
        echo ""
        echo "### Next Steps:"
        echo "1. Verify the app is running at: https://attackacrack-prod-5ce6f.ondigitalocean.app"
        echo "2. Check that authentication works properly"
        echo "3. Verify OpenPhone sync functionality"