name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
      tag:
        description: 'Docker image tag to deploy (leave empty for latest)'
        required: false
        type: string

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: attackacrack-crm
  APP_ID: 4d1674ef-bfba-4fd3-9a97-943fa02c1f70  # Fixed app ID

jobs:
  deploy:
    name: Deploy to DigitalOcean App Platform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Determine image tag
      id: image-tag
      run: |
        if [ -z "${{ github.event.inputs.tag }}" ]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        fi
        echo "Using image tag: ${{ github.event.inputs.tag || 'latest' }}"
    
    - name: Update app spec with new image tag
      run: |
        # Copy the app spec
        cp .do/app.yaml .do/app-deploy.yaml
        
        # Only update the Docker image tag - nothing else
        sed -i "s/tag: latest/tag: ${{ steps.image-tag.outputs.tag }}/g" .do/app-deploy.yaml
        
        echo "Updated app spec to use tag: ${{ steps.image-tag.outputs.tag }}"
        
        # Show what we're deploying
        echo "=== Image configuration ==="
        grep -A 3 "image:" .do/app-deploy.yaml | head -10
    
    - name: Validate app spec
      run: |
        echo "Validating app specification..."
        doctl apps spec validate .do/app-deploy.yaml
    
    - name: Deploy to DigitalOcean
      run: |
        echo "Deploying to app ID: ${{ env.APP_ID }}"
        
        # Show current app status
        echo "=== Current app status ==="
        doctl apps get ${{ env.APP_ID }} --format ID,Status,DefaultIngress --no-header
        
        # Update the app with the new spec
        # This will preserve all existing environment variables
        echo "=== Updating app with new spec ==="
        doctl apps update ${{ env.APP_ID }} --spec .do/app-deploy.yaml --wait
        
        echo "Deployment initiated successfully"
    
    - name: Get deployment status
      run: |
        echo "=== Getting latest deployment status ==="
        DEPLOYMENT_ID=$(doctl apps list-deployments ${{ env.APP_ID }} --format ID --no-header | head -1)
        echo "Latest deployment ID: $DEPLOYMENT_ID"
        
        doctl apps get-deployment ${{ env.APP_ID }} $DEPLOYMENT_ID
    
    - name: Verify health check
      run: |
        echo "Waiting 30 seconds for deployment to stabilize..."
        sleep 30
        
        # Get the app URL
        APP_URL=$(doctl apps get ${{ env.APP_ID }} --format DefaultIngress --no-header)
        echo "App URL: $APP_URL"
        
        # Test health endpoint
        echo "=== Testing health endpoint ==="
        if curl -f -s -o /dev/null -w "%{http_code}" $APP_URL/health | grep -q "200"; then
          echo "✅ Health check passed!"
        else
          echo "❌ Health check failed"
          
          # Get logs for debugging
          echo "=== Recent deployment logs ==="
          DEPLOYMENT_ID=$(doctl apps list-deployments ${{ env.APP_ID }} --format ID --no-header | head -1)
          doctl apps get-logs ${{ env.APP_ID }} --type=deploy --deployment=$DEPLOYMENT_ID --tail=50
          
          exit 1
        fi
    
    - name: Summary
      if: success()
      run: |
        APP_URL=$(doctl apps get ${{ env.APP_ID }} --format DefaultIngress --no-header)
        echo "## 🚀 Deployment Successful!"
        echo ""
        echo "- **Environment**: ${{ github.event.inputs.environment }}"
        echo "- **Image Tag**: ${{ steps.image-tag.outputs.tag }}"
        echo "- **App URL**: $APP_URL"
        echo "- **Deployed by**: ${{ github.actor }}"
        echo ""
        echo "The application is now live and all secrets are preserved."