name: Test Secrets Access

on:
  workflow_dispatch:

jobs:
  test-secrets:
    name: Test Secret Access
    runs-on: ubuntu-latest
    
    steps:
    - name: Check secrets
      run: |
        echo "Testing secret access (will show 'set' or 'not set', not values):"
        echo ""
        echo "DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN != '' && 'SET' || 'NOT SET' }}"
        echo "SECRET_KEY: ${{ secrets.SECRET_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "REDIS_URL: ${{ secrets.REDIS_URL != '' && 'SET' || 'NOT SET' }}"
        echo "CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL != '' && 'SET' || 'NOT SET' }}"
        echo "CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND != '' && 'SET' || 'NOT SET' }}"
        echo "OPENPHONE_API_KEY: ${{ secrets.OPENPHONE_API_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "OPENPHONE_WEBHOOK_SIGNING_KEY: ${{ secrets.OPENPHONE_WEBHOOK_SIGNING_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "OPENPHONE_PHONE_NUMBER: ${{ secrets.OPENPHONE_PHONE_NUMBER != '' && 'SET' || 'NOT SET' }}"
        echo "OPENPHONE_PHONE_NUMBER_ID: ${{ secrets.OPENPHONE_PHONE_NUMBER_ID != '' && 'SET' || 'NOT SET' }}"
        echo "POSTGRES_URI: ${{ secrets.POSTGRES_URI != '' && 'SET' || 'NOT SET' }}"
        echo ""
        echo "If any show 'NOT SET', they need to be added to GitHub Secrets"